Update test2.yml

diff --git a/.github/workflows/test2.yml b/.github/workflows/test2.yml
--- a/.github/workflows/test2.yml
+++ b/.github/workflows/test2.yml
@@ -24,7 +24,24 @@ jobs:
             sudo pip3 install firebase_admin
             sudo pip3 install telebot
             
-        - name: Test
+        - name: download
           run: |
-            context_string=$(awk '/\.registers/, /\.end method/' "test.txt")
-            echo $context_string
+            mkdir -p tmp
+            cd tmp
+            axel -n $(nproc) https://github.com/VPT-bit/Patch_China_Rom_Haydn/releases/download/alpha/boot.img
+            axel -n $(nproc) https://github.com/VPT-bit/Patch_China_Rom_Haydn/releases/download/alpha/ksud
+            axel -n $(nproc) https://github.com/VPT-bit/Patch_China_Rom_Haydn/releases/download/alpha/ksud.d
+            
+        - name: patch boot
+          run: |
+            [ -f tmp/boot.img ] && echo "Download successfully" || echo "Failed to download"
+            [ ! -f tmp/ksud ] && echo "Binary not found" || echo "Fine"
+            chmod a+x tmp/ksud
+            ./tmp/ksud boot-patch --boot tmp/boot.img --magiskboot tmp/magiskboot --kmi android12-5.10
+            
+        - name: upload artifact
+          uses: actions/upload-artifact@v4
+          with:
+            name: boot_ksu_patch
+            path: tmp/*.img
+            
