Update test2.yml

diff --git a/.github/workflows/test2.yml b/.github/workflows/test2.yml
--- a/.github/workflows/test2.yml
+++ b/.github/workflows/test2.yml
@@ -27,3 +27,4 @@ jobs:
         - name: Test
           run: |
             echo $(pwd)
+            [ -f test.sh ] && echo "done" || echo "fail"
